import java.awt.BorderLayout;
import java.time.LocalDate;

public class DashBoard extends javax.swing.JFrame {
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    /** Creates new form DashBoard */
    public DashBoard() {
        initComponents();
        Setdate();
        
    // Establecer tamaño minimo y maximo para la ventana
    setMinimumSize(new java.awt.Dimension(990, 630));
    setMaximumSize(new java.awt.Dimension(990, 630));
    
    // Deshabilitar la capacidad de redimensionar la ventana
    setResizable(false);
    
    //Establecer la primera ventana que se vera
    Principal1 P1 = new Principal1();
    P1.setSize(760, 630);
    P1.setLocation(0, 0);
    
    Contenido.removeAll();
    Contenido.add(P1, BorderLayout.CENTER);
    Contenido.revalidate();
    Contenido.repaint();
        
        
    }

    private void Setdate(){
        LocalDate now = LocalDate.now();
        int Year = now.getYear();
        int Dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre",
        "Octubre", "Noviembre", "Diciembre"};
        dateText.setText("Hoy es "+Dia+" de "+meses[month - 1]+" del "+Year);
        }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        PanelMenu = new javax.swing.JPanel();
        BtnInicio = new javax.swing.JButton();
        BtnVentas = new javax.swing.JButton();
        BtnRventas = new javax.swing.JButton();
        dateText = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        BtnCocina = new javax.swing.JButton();
        Btnproducto = new javax.swing.JButton();
        Contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(990, 630));

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        BackGround.setForeground(new java.awt.Color(255, 255, 255));
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMenu.setBackground(new java.awt.Color(204, 0, 0));
        PanelMenu.setForeground(new java.awt.Color(204, 0, 0));
        PanelMenu.setPreferredSize(new java.awt.Dimension(230, 630));

        BtnInicio.setBackground(new java.awt.Color(255, 255, 255));
        BtnInicio.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        BtnInicio.setForeground(new java.awt.Color(255, 255, 255));
        BtnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/inicio.png"))); // NOI18N
        BtnInicio.setText(" INICIO MENU");
        BtnInicio.setContentAreaFilled(false);
        BtnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnInicio.setIconTextGap(10);
        BtnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInicioActionPerformed(evt);
            }
        });

        BtnVentas.setBackground(new java.awt.Color(255, 255, 255));
        BtnVentas.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        BtnVentas.setForeground(new java.awt.Color(255, 255, 255));
        BtnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Menu.png"))); // NOI18N
        BtnVentas.setText("VENTAS");
        BtnVentas.setContentAreaFilled(false);
        BtnVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnVentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnVentas.setIconTextGap(10);
        BtnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVentasActionPerformed(evt);
            }
        });

        BtnRventas.setBackground(new java.awt.Color(255, 255, 255));
        BtnRventas.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        BtnRventas.setForeground(new java.awt.Color(255, 255, 255));
        BtnRventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/estadisticas.png"))); // NOI18N
        BtnRventas.setText("REPORTE VENTAS");
        BtnRventas.setContentAreaFilled(false);
        BtnRventas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRventas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnRventas.setIconTextGap(10);
        BtnRventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRventasActionPerformed(evt);
            }
        });

        dateText.setBackground(new java.awt.Color(255, 255, 255));
        dateText.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        dateText.setForeground(new java.awt.Color(255, 255, 255));
        dateText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateText.setText("HOY ES 31 DE SEPTIEMBRE DEL 2024");
        dateText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo.png"))); // NOI18N

        BtnCocina.setBackground(new java.awt.Color(255, 255, 255));
        BtnCocina.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        BtnCocina.setForeground(new java.awt.Color(255, 255, 255));
        BtnCocina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Cocina.png"))); // NOI18N
        BtnCocina.setText("COCINA Y ORDENES");
        BtnCocina.setContentAreaFilled(false);
        BtnCocina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCocina.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnCocina.setIconTextGap(10);
        BtnCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCocinaActionPerformed(evt);
            }
        });

        Btnproducto.setBackground(new java.awt.Color(255, 255, 255));
        Btnproducto.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        Btnproducto.setForeground(new java.awt.Color(255, 255, 255));
        Btnproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/estado.png"))); // NOI18N
        Btnproducto.setText("PRODUCTOS");
        Btnproducto.setContentAreaFilled(false);
        Btnproducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btnproducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Btnproducto.setIconTextGap(10);
        Btnproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnproductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dateText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnCocina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btnproducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnRventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addComponent(BtnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btnproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnRventas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, Short.MAX_VALUE)
                .addGap(164, 164, 164))
        );

        BackGround.add(PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        Contenido.setBackground(new java.awt.Color(255, 255, 255));
        Contenido.setForeground(new java.awt.Color(255, 255, 255));
        Contenido.setMaximumSize(new java.awt.Dimension(760, 630));
        Contenido.setMinimumSize(new java.awt.Dimension(760, 630));

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        BackGround.add(Contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 760, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInicioActionPerformed
        Principal1 P1 = new Principal1();
        P1.setSize(760, 630);
        P1.setLocation(0, 0);
        
        Contenido.removeAll();
        Contenido.add(P1, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_BtnInicioActionPerformed

    private void BtnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVentasActionPerformed
        Ventas V1 = new Ventas();
        V1.setSize(760, 630);
        V1.setLocation(0, 0);
        
        Contenido.removeAll();
        Contenido.add(V1, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_BtnVentasActionPerformed

    private void BtnCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCocinaActionPerformed
        Cocina C1 = new Cocina();
        C1.setSize(760, 630);
        C1.setLocation(0, 0);
        
        Contenido.removeAll();
        Contenido.add(C1, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_BtnCocinaActionPerformed

    private void BtnproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnproductoActionPerformed
        Productos P1 = new Productos();
        P1.setSize(760, 630);
        P1.setLocation(0, 0);
        
        Contenido.removeAll();
        Contenido.add(P1, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_BtnproductoActionPerformed

    private void BtnRventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRventasActionPerformed
        Reportes R1 = new Reportes();
        R1.setSize(760, 630);
        R1.setLocation(0, 0);
        
        Contenido.removeAll();
        Contenido.add(R1, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_BtnRventasActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JButton BtnCocina;
    private javax.swing.JButton BtnInicio;
    private javax.swing.JButton BtnRventas;
    private javax.swing.JButton BtnVentas;
    private javax.swing.JButton Btnproducto;
    private javax.swing.JPanel Contenido;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JLabel dateText;
    // End of variables declaration//GEN-END:variables
}
